# config for logger
logger:
  level: INFO
  name: IAAPyTorch
# config for trainer
trainer:
  name: ClassificationTrainer
  params:
    run_dir: runs
    run_id: nima-distribution
    batch_size: 256
    epoch: 120
    gpu: !!python/list [ 2, 3 ]
    log_every: 5
    num_workers: 6
    seed: 1234
#    base_lr: 0.0005
#    head_lr: 0.005
# config for dataset
dataset:
  name: AVAAestheticDistributionDataset
  params:
    root: /home/liulizhao/datasets/AVA_dataset
# config for model
model:
  name: NIMA
  params:
    base_name: resnet50
    num_classes: 10
# config for loss function
loss:
  name: EarthMoverDistanceLoss
  params:
    r: 2.0
# config for optimizer
optimizer:
  name: SGD
  params:
    lr: 0.005
    weight_decay: 0.00001
    momentum: 0.9
# config for lr scheduler
lr_scheduler:
  name: StepLR
  params:
    step_size: 10
    gamma: 0.95
# config for metric
metric:
  name: AccuracyFromDistribution
  params:
    cut_off: 5.0
# config for training transformation
train_transforms:
  - name: Scale
    params:
      size: 256
  - name: RandomFiveCrop
    params:
      size: 224
  - name: RandomHorizontalFlip
    params:
      p: 0.5
  - name: ToTensor
  - name: Normalize
    params:
      mean: !!python/list [ 0.485, 0.456, 0.406 ]
      std: !!python/list [ 0.229, 0.224, 0.225 ]
# config for test transformation
test_transforms:
  - name: Scale
    params:
      size: 256
  - name: CenterCrop
    params:
      size: 224
  - name: ToTensor
  - name: Normalize
    params:
      mean: !!python/list [ 0.485, 0.456, 0.406 ]
      std: !!python/list [ 0.229, 0.224, 0.225 ]